name: Lint & Tests

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  test:
    name: Code Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      #     - uses: actions/cache@v2
      #       id: cache-pip
      #       with:
      #         path: ~/.cache/pip
      #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #         restore-keys: |
      #           ${{ runner.os }}-pip-

      - name: Install OS dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          # sudo apt install build-essential libpoppler-cpp-dev pkg-config python3-dev
          python -m pip install --upgrade pip
      - name: Install pip dependencies
        #       if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt
      - name: Formatting with black
        uses: jpetrucciani/black-check@master
        with:
          path: '.'

      - name: Lint api with flake8
        run: |
          pip install flake8
          flake8 app --count --max-line-length=100 --show-source --statistics

      - name: Test code with pytest
        working-directory: ./api
        env:
          PROJECT_NAME: ${{secrets.PROJECT_NAME}}
          PROJECT_DESCRIPTION: ${{secrets.PROJECT_DESCRIPTION}}
          API_ROOT_PATH: ${{secrets.API_ROOT_PATH}}
        run: |
          pip install pytest
          python -m pytest tests -v -s
